apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name}}
  name: {{ .Release.Name}}
spec:
  replicas: {{ .Values.deploy.replicas}}
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
<<<<<<< HEAD
      - image: nginx:1.21
=======
      - image: nginx
>>>>>>> 7923a9717fcd3494d345b979b799497f65a5e7f3
        name: nginx
        resources: {}
status: {}

