apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name}}
  name: {{ .Release.Name}}
spec:
  replicas: {{ .Values.deploy.replicas}}
  selector:
    matchLabels:
      app: {{ .Release.Name}}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.21
        name: {{ .Release.Name}}
        resources: {}
status: {}
