apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name}}-svc
  name: {{ .Release.Name}}-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name}}
  type: NodePort
status:
  loadBalancer: {}
